services:
  api:
    build:
      context: ./api_service
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api_service:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/posts_db
    depends_on:
      db:
        condition: service_healthy


  bot:
    build:
      context: ./bot_service
      dockerfile: Dockerfile
    volumes:
      - ./bot_service:/app
    env_file:
      - .env
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api


  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=posts_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
